### ISSUE TITLE
Ping Nodes

### ISSUE THREAD

**Issue by titus450** [TMRh20/RF24Mesh#117]
Is there a way of checking each node connection ? (ping)

i try to send a packet with no data while i loop though mesh.addrList to check whether i get a 1 or 0
to determine if the node is still alive or not but it only seems to work when nodes are connected directly to the master node. When a node is a child of another node, the master node cannot ping this node. What it does is that it pings the parent node of the child node and return the value 1 directly. It does not continue to check whether the child node is still online.

So i was wondering if there is a way to ping child nodes.

**Comment by Avamander** [comment]
Take the basic concept of pinging and implement that. 

Here's an example:

> Can you hear me?

> Yes
