### ISSUE TITLE
Making a supported list of libraries that can be used alongside RF24Mesh (and other RF24* libraries)

### ISSUE THREAD

**Issue by Avamander** [TMRh20/RF24Mesh#21]
It would be really nice to have a list of libraries that can be used alongside RF24* libraries without worrying about compatibility issues. Supported libraries could have three status' "Fully compatible", "Possible conflict" and "Incompatible". This would be really useful for those who wish to use many libraries at once.

**Comment by TMRh20** [comment]
This would be useful, but not something I have the knowledge to compile, thought the list can start here.
Theoretically, just about any library should be compatible, because SPI can be handled via hardware or software, and that is about the only thing needed.
