### ISSUE TITLE
Problem on Arduino Mega

### ISSUE THREAD

**Issue by ricmail85** [TMRh20/RF24Mesh#35]
Dear TMRh20,

I'm trying to setup a mesh network with 2 arduinos, one nano and one mega. By loading the examples on the nano I don't have problems. On the mega, after loading, the program hold on the mesh.update line... The mesh.begin is ok, but it does not goes beyond mesh.update... 

Do you know why? I tried changing the radios but it is the same... It seems related to the arduino MEGA board... But I'm sure it works because I used a lot.

bye!

**Comment by Avamander** [comment]
Check your wiring and DEFINITELY solder a capacitor to the 3.3V and GND pins on the radio, Mega's 3.3V regulator is quite crappy. Report the results after doing so.

**Comment by ricmail85** [comment]
Hi, thanks for the reply. I tried adding a 10 uF capacitor (I have this one at the moment) but the behavior is the same... sketch stucks at mesh.update() on the mega...

**Comment by Avamander** [comment]
Check wiring. Attach bigger cap.

**Comment by ricmail85** [comment]
Ok, I'll give it a try later and I'll let you know.
thanks again

**Comment by ricmail85** [comment]
Ok, the problem was I didn't know that the MEGA has different SPI pins. I solved setting on the MEGA the pins as: CE(40), CSN(53), MOSI(51), MISO(50), SCK(52)
while on the nano I followed the usual ones: CE(7), CSN(8), MOSI(11), MISO(12), SCK(13)

bye!
