### ISSUE TITLE
write error

### ISSUE THREAD

**Issue by koverg70** [TMRh20/RF24Mesh#39]
I created a master (0) and one child node (1). The child node gets an address, and sends a payload (millis) to master. Master receives it, but on the childe the write returns false. Then the checkConnectivity returns false also. So it renews the address which is successful.

There must be some problem with the master ACK-ing the payload. But communication seems to work both ways, because child gets the address OK. What should I do the debug this problem?

Edit: I used RF24 library before, but as long as I remember my previous project didn't use auto ACK.

Edit2: May be I have an incompatible chip and should disable dynamic payload?

Edit3: commented out #define ENABLE_DYNAMIC_PAYLOADS in network config header, but this is even worse, no address is given, and of course no payload is on master

**Comment by TMRh20** [comment]
Are you testing with the included examples?

If so, its usually best to work down the stack, so test with RF24Network examples, and if no luck, test with RF24 examples. The idea is to narrow down the trouble to the appropriate layer, or to a physical/hardware issue if it doesn't work properly at all.

**Comment by koverg70** [comment]
The problem is at the radio layer for sure. The packet arrives but the auto acknowledgement not working. Unsure wether the receiveds doesn't sends back or the oridinal sender doesn't receives.

It is known that some chips are false and it is suggested (even in the network config header), that I should disable dynamic payloads. The problem is, that when I disable it mesh stops working, de child nodes cannot allocate addresses. (Of course I updated the code on each node.)

**Comment by TMRh20** [comment]
Are you testing with the included examples?

If so, its usually best to work down the stack, so test with RF24Network examples, and if no luck, test with RF24 examples. The idea is to narrow down the trouble to the appropriate layer, or to a physical/hardware issue if it doesn't work properly at all.

**Comment by koverg70** [comment]
Have you tried the current RF24Mesh code with #define ENABLE_DYNAMIC_PAYLOADS commented out? Does it work for you?

**Comment by TMRh20** [comment]
Sorry, I thought you were asking for my assistance. If you so adamantly refuse to cooperate, you must understand that must refuse any further attempts at helping you.
