### ISSUE TITLE
Automatic address release on master

### ISSUE THREAD

**Issue by efsantana** [TMRh20/RF24Mesh#47]
Whenever I have two connected nodes on the mesh network and I turn the non-master off, the master still displays it in the monitor. 

I know that every node should release its address before shutting down, but what if something unexpected happens like dead battery or damaged node? The node wouldn't release its address in these cases. So the master could check if the nodes are alive and manage the list automatically.

Is it possible to have the master do this automatically or I'll have to do it myself?

**Comment by TMRh20** [comment]
> Whenever I have two connected nodes on the mesh network and I turn the non-master off, the master still displays it in the monitor.

The master displays active registrations, not necessarily active nodes.

> Is it possible to have the master do this automatically or I'll have to do it myself?
 
Yourself. There are many ways of configuring the network, so I don't know of a way off-hand to have the master manage this that will suit all or most scenarios. You can use the new setAddress(); function to zero out the RF24Network address of an inactive nodeID.
