### ISSUE TITLE
Maximum number of nodes on network

### ISSUE THREAD

**Issue by efsantana** [TMRh20/RF24Mesh#51]
One can only assign nodeIDs from 0 to 255. 

Does this mean that the network can only have 256 nodes? How can I have more nodes and still uniquely identify them?

**Comment by TMRh20** [comment]
> Does this mean that the network can only have 256 nodes?

Yup, thats about the max though I doubt the mesh would function well with
that many nodes.

> How can I have more nodes and still uniquely identify them?

Use RF24Network with multicast disabled (780 nodes max)

**Comment by efsantana** [comment]
And why is there this limitation?

**Comment by TMRh20** [comment]
Limited radio pipes.

1
4
16
64
256
Total: 341

1
5
25
125
625
Total: 781

https://www.nordicsemi.com/chi/content/download/2730/34105/file/nRF24L01_Product_Specification_v2_0.pdf

**Comment by robertiko07** [comment]
nodes on network is about 781, but nodes IDs?
