### ISSUE TITLE
Sleeping Nodes with RF24Mesh

### ISSUE THREAD

**Issue by tjb8907** [TMRh20/RF24Mesh#61]
I am building a sensor network for my home using nRF24L01 Radios. So far it consists of a master node that has my sheild that connect to my SmartThings Hub for my Z-wave network. This basically relays the messages it receives from the nodes to the SmartThings Hub and it processes them the way I need to.

The nodes consist so far of contact sensors and PIR Motion sensors. They run a sketch that sleeps in powerdown mode, and powers down the radio, and uses interrupts to wake up when the state of the sensor changes. That all works great, with only 4 node (all children of the master). Once I try to add 5th, it can't doesn't work because it's parent is sleeping. 

Is this a limitation of the library, or is there a way to wake the node using the radio interrupt when it needs to route a message to the master? I have done a little testing, but haven't gotten far....figure I would ask before digging too deep.

I am playing with the sleepNode() function from the RF24Network Library but I can't get it to wake up to relay a message. Most my nodes aren't going to be moving around physically, so I could use just RF24Network if sleepNode() works with that, but I really like the dynamic part of Mesh, so I would like to stick with it if possible.

I can upload the sketches that I'm using, but I'm mostly just wondering if its even possible.

Thanks,
Tom

Afterthought EDIT: If a node can be awoken by sending directly to it. I would be open to implementing code that just sends to it's parent, or even sends a message to its parent that causes it to stay awake long enough to route the message. The problem I see with that is I can't even get the 5th node to connect to the Mesh because it doesn't see any nodes to connect through.

I'm trying to run battery powered nodes, so I want them to sleep as much as possible. I could have them wake every so often (even if its a minute) to allow a child to register.

**Comment by Avamander** [comment]
As nRF24L01+ do not have wake-on-radio function (if they had you could use it to wake up the Arduino). You must implement a system to wake up the nodes yourself with interrupts and somehow either synchronize the wakeup or change the topology of the mesh.
