### ISSUE TITLE
Dual Headed Operation

### ISSUE THREAD

**Issue by danielebuso** [TMRh20/RF24Mesh#62]
Hello, is there a way to use the "Dual Headed Operation" that is available with the RF24Network library?
Thanks, Regards

**Comment by Avamander** [comment]
I am not aware if RF24Mesh utilized dual headed operation fully, but you can always try (set it up as RF24Network documentation says).

**Comment by TMRh20** [comment]
Not really, the dual headed operation was never fully realized properly, and doesn't add much benefit for the potential troubles.
