### ISSUE TITLE
Adding lib to platform.io registry

### ISSUE THREAD

**Issue by jeanmatthieud** [TMRh20/RF24Mesh#67]
Hi,

Could you add your lib to platform.io registry, as you did for RF24 ?
Same question for RF24Network.

Thanks for your work !

JM

**Comment by harmon25** [comment]
RF24Network is on the registry (ID: 435)

Just created a pull request to add library.json to this repo. #68

**Comment by jeanmatthieud** [comment]
Great news !

**Comment by Avamander** [comment]
Submitted the request.
