### ISSUE TITLE
Weak signal only few meters without any wall

### ISSUE THREAD

**Issue by CROSP** [TMRh20/RF24Mesh#75]
Hi, thanks for great library but I have problem with setting up network. The problem is that signal is very weak it cannot even path the wall and works facing directly to the other sensor. 
I tried to do something like this 
`  mesh.begin(DEFAULT_MESH_CHANNEL,RF24_250KBPS,MESH_RENEWAL_TIMEOUT);`

**Comment by Avamander** [comment]
What modules?

>
