### ISSUE TITLE
Random mesh connecting behavior

### ISSUE THREAD

**Issue by maricel86** [TMRh20/RF24Mesh#77]
Hello, 

I have an issue with RF24Mesh.

This is a simple case : 
- 1 master  (mesh.begin() , mesh.update(), mesh.dhcp() )
- 1 slave (mesh.begin() , mesh.update())

First time when i deployed on devices, all went well.
After adding **one Serial.println() line**, the slave was blocking in mesh.begin(); **This behavior was consistent.**
If i remove the print line, all worked OK. **Also, consistent**.
The devices are at** 5 cm distance** and i **never changed the position**. 

I've tried to debug to find out and found that the cod was executing like that :

=>  bool RF24Mesh::begin(uint8_t channel, rf24_datarate_e data_rate, uint32_t timeout)
=>  uint16_t RF24Mesh::renewAddress(uint32_t timeout)
=>  bool RF24Mesh::requestAddress(uint8_t level)
=>  bool RF24Network::multicast(RF24NetworkHeader& header,const void* message, uint16_t len, uint8_t level)
=>  bool RF24Network::write(RF24NetworkHeader& header,const void* message, uint16_t len, uint16_t writeDirect)
=> bool RF24Network::_write(RF24NetworkHeader& header,const void* message, uint16_t len, uint16_t writeDirect)
=> bool RF24Network::write(uint16_t to_node, uint8_t directTo) 
=> bool RF24Network::write_to_pipe( uint16_t node, uint8_t pipe, bool multicast )
=> bool RF24::writeFast( const void* buf, uint8_t len, const bool multicast )

When error occurs, the execution is the folowing:

send_node = 0 , send_pipe = 0, multicast = 1, from_node= 2340
send_node = 1 , send_pipe = 0, multicast = 1, from_node= 2340
send_node = 8 , send_pipe = 0, multicast = 1, from_node= 2340
send_node = 64 , send_pipe = 0, multicast = 1, from_node= 2340
blocking in writeFast because  _BV(TX_FULL) is always true (get_status() is 15)

When all is OK, the execution is the following :

send_node = 0 , send_pipe = 0, multicast = 1, from_node= 2340
send_node = 1 , send_pipe = 0, multicast = 1, from_node= 2340
send_node = 0 , send_pipe = 4, multicast = 0, from_node= 4

Execution success is consistent. Seems some how to be linked to Serial.println

**Comment by TMRh20** [comment]
First thing would be to make sure you have the latest versions of the libraries. Easiest is with Arduino library manger.

If that doesn't help, can you post the exact code you are using on the slave with the println added?
Also what devices are you using?
