### ISSUE TITLE
RF24mesh-master  compiling error

### ISSUE THREAD

**Issue by Toumi7** [TMRh20/RF24Mesh#85]
hello @TMRh20 

i'm trying to use the RF24mesh-master library to build a mesh netWork 
i wanted to try the "RF24Mesh_Example_Master.ino" but when compiling i get errors that belong to the RF24Network  library ( compiling result in the screenshot) 
can you please help me to find a solution for this , i'm using that in my graduation project 
sorry for my poor english 

![capture](https://cloud.githubusercontent.com/assets/19973410/16195221/81f5371a-36f0-11e6-9c49-15a14b782499.PNG)

**Comment by Avamander** [comment]
Make sure all your libraries are up-to-date. Use the Arduino IDE to update
them.
