### ISSUE TITLE
I am unable to setup a dynamic mesh 

### ISSUE THREAD

**Issue by rohinrohin** [TMRh20/RF24Mesh#87]
**Setup:**
I have setup the master as from the example, (master to node msg) and have three nodes in the system as  

- 0-master
- 1-node1 
- 2-node2. 

I have setup the master to send a message to node2(2) every 5 seconds. 
It works like it should when the master is in range of node2. 

**The problem:**
When master is in range of node1 and node1 is in range of node2 (but node2 not in range of master). The master does not detect node2 at all. Is there anything I can do or am I doing something wrong?

Thanks

**Comment by TMRh20** [comment]
In the same situation, does the master receive information if using the
rf24mesh_example_master rf24mesh_example sketches?

If you can monitor the end node using a laptop etc, please edit
RF24Mesh_config.h and uncomment #define MESH_DEBUG then reload Arduino &
please post the results.

**Comment by rohinrohin** [comment]
Sorry for the delay. I will do that and send it to you asap.

**Comment by rohinrohin** [comment]
Got it working, thanks!
