### ISSUE TITLE
Issue with handling data

### ISSUE THREAD

**Issue by dekundu** [TMRh20/RF24Mesh#90]
Hi,
I am using a data structure called Request that has a core data structure called Device and using uint32_t type messageId to put the millis() as the message identifier. 
```
struct Request{
 Device device;
 uint32_t messageId;
}
```
The size of the Request variable I printed using sizeof was 16. During sending I checked that the struct variable is getting constructed properly but at the receiving end I get the device object intact but the messageId gets zero. I was looking into the library code a bit and found that first 8 bytes are for header, then next two bytes are for buffer size and then the data comes, so ideally i should be able to send 22 bytes. But the size it considers is min(buffersize, sizeof(struct))
Plaese help me here to send the data, is there any way to adjust the bufferSize?
EDIT: 
Its due to struct padding and alignment issue. But the alignment works as expected in esp (16) but in arduino it does not use any padding and returns exact size (12), so at the recipient end (arduino) the size does not get matched, and the read at arduino end does not work properly.

**Comment by arenddeboer** [comment]
Thanks for researching and posting your findings. I think I've hit the same issue between an Arduino Pro Mini AVR board and an ESP8266 NodeMCU v0.9. Sending a struct from avr to esp results in some weird deserializing on the other end. Did you find a way around this ?
